version: '3.3'

services:
  backend-dev:
    build: ./app
    command: ["npm", "run", "dev"]
    ports:
      - "8080:8080"
    volumes:
      - "./app:/usr/src/app"
      - "/usr/src/app/node_modules"
    environment:
      - NODE_ENV=development

  frontend-dev:
    build: ./app/frontend
    environment:
      - REACT_APP_API_URL=http://backend-dev/api
      - CHOKIDAR_USEPOLLING=true
      - NODE_ENV=development
    volumes:
      - "./app/frontend:/usr/src/app"
      - "/usr/src/app/node_modules"
    ports:
      - "3000:3000"

  build-linux:
    image: electronuserland/builder
    environment:
      - USE_HARD_LINKS=false
    volumes:
        - ".:/project"
    command: ["npm", "run", "dist"]

